name: Github Action Workflow PROD

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - ci-cd-prd
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-cd-prd:
    uses: ORT-Proyecto-DevOps/vue-app/.github/workflows/ci_cd_pipeline.yml@main
    with:
      CI_ENV: production
      CONTENTFUL_ENVIRONMENT: 'main'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET_PRD }}
      SONAR_TOKEN_VUE_APP: ${{ secrets.SONAR_TOKEN_VUE_APP }}
