name: Github Action Workflow DEV

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  repository_dispatch:
    types:
      - ci-cd-dev
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-cd-dev:
    uses: ORT-Proyecto-DevOps/orders-service-example/.github/workflows/ci_cd_pipeline.yml@develop
    with:
      IMAGE_TAG: 'orders-service-develop'
      BRANCH: 'develop'
      ENV: 'dev'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      SONAR_TOKEN_ORDERS_SERVICE: ${{ secrets.SONAR_TOKEN_ORDERS_SERVICE }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      


